### ISSUE TITLE
Attach volume required?

### ISSUE THREAD

**Issue by zemien** [DanWahlin/AspNetCorePostgreSQLDockerApp#10]
I'm testing out manual linking using the following command but it fails with an error that it cannot find a .sln or .csproj to build:
https://github.com/DanWahlin/AspNetCorePostgreSQLDockerApp/blob/3c05af3ce1d460b7628808d9c06953241e5403a4/AspNetCorePostgreSQLDockerApp/aspnetcore.development.dockerfile#L29

I resolved it by attaching a volume to it, by adding `-v $(pwd):/var/www/aspnetcoreapp` whereby the current directory is where the .csproj file is. It didn't work if my present directory was where the .sln is.

The issue is: Is there a scenario where the given code snippet should work, without me having to add a volume?

**Comment by DanWahlin** [comment]
That's correct. If you're running the development version then it wouldn't know where to find the code to build unless you (a) copy the code into the image or (b) use a volume to point to the project. That's something shown in the Pluralsight course if that's what you're following along with - sounds like you already figured it out though so great job!
