### ISSUE TITLE
docker up failed for creating volume

### ISSUE THREAD

**Issue by cbaurand** [DanWahlin/AspNetCorePostgreSQLDockerApp#11]
Hi Dan,

I followed exactly what you wrote but i get the following error when i do docker-compose up:
ERROR: for aspnetcoreapp  Cannot create container for service web: invalid volume specification: 'D:\test\AspNetCorePostgreSQLDockerApp-master\AspNetCorePostgreSQLDockerApp:/var/www/aspnetcoreapp:rw'

I work on windows 10.
Any idea ?
Thanks.

**Comment by DanWahlin** [comment]
Volumes are configured to be on your C drive in the Users folder by default on Windows. You'll need to move the folder to that location. See the Docker Desktop settings screen for more info.
