### ISSUE TITLE
.net core 2

### ISSUE THREAD

**Issue by jhallam3** [DanWahlin/AspNetCorePostgreSQLDockerApp#7]
Hey Dan, 

Just tied this with .net core 2 and get the following 

Data/ApplicationDbContext.cs(16,18): error CS0311: The type 'Dashboard.Models.ApplicationUser' cannot be used as type parameter 'TUser' in the generic type or method 'IdentityDbContext<TUser>'. There is no implicit reference conversion from 'Dashboard.Models.ApplicationUser' to 'Microsoft.AspNetCore.Identity.IdentityUser'. [/Users/JonHallam2/project new /Dashboard/DashboardCoreVs2017-2/Dashboard.csproj]

**Comment by DanWahlin** [comment]
Thanks. This project is for V1.1 at this point. I'll look at 2 for it once it's released.
