### ISSUE TITLE
Manually building image results in docker build error

### ISSUE THREAD

**Issue by zemien** [DanWahlin/AspNetCorePostgreSQLDockerApp#9]
I'm going through Chapter 7 and trying to run this command manually in the terminal:

https://github.com/DanWahlin/AspNetCorePostgreSQLDockerApp/blob/3c05af3ce1d460b7628808d9c06953241e5403a4/AspNetCorePostgreSQLDockerApp/aspnetcore.development.dockerfile#L23

I get the following error:
````
ZemienMacbook:AspNetCorePostgreSQLDockerApp zemien$ docker build -f aspnetcore.development.dockerfile -t zemien/dotnet:1.0.0 
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile
````
I have replaced [yourDockerHubID] with a username, but I also get the same error if I remove the whole tag option and leave -f in there.

I should note that the containers work when I use docker-compose build and docker-compose up, as outlined in Readme.md. But I wanted to build up my layers of knowledge by following the example.

System info:

- Mac OS Mojave
- Docker CE 2.0.0.3
- Docker Engine 18.09.2

Any advice is appreciated!

**Comment by DanWahlin** [comment]
Hi Zemien. You're just missing the "." at the end of the build statement. That's shown in the course a bunch but I need to update the comment in that particular file since it wasn't showing there.
